### ISSUE TITLE
Custom Mapping for Heroes Controller Hook crashes when i press the "Map Me!" Button

### ISSUE THREAD

**Issue by joaomiguel-sb** [Sewer56/Heroes.Controller.Hook.ReloadedII#1]
Exactly what the title says.
Also when i try using a Xinput controller without the mapping the analogs don't work.
I'm using Window 10 x64, I don't know the kind of info I need to report this so If I'm missing something, please tell me so I can give you the info.
Thanks in advance.

**Comment by Sewer56** [comment]
Could you pop open Event Viewer and go to Windows Logs -> Application.
Run the program, let it crash and find the most recent entry in Event Viewer marked as `Error` with Source being `.NET Runtime`

![image](https://user-images.githubusercontent.com/6697380/111087846-d808d200-851b-11eb-9f37-6f5a9d70a356.png)
(Reference)

Select the error with .NET Runtime, right click, save, zip and upload here.

**Comment by joaomiguel-sb** [comment]
[runtimeerror.zip](https://github.com/Sewer56/Heroes.Controller.Hook.ReloadedII/files/6137870/runtimeerror.zip)
I got an application error too, so I put it in there.

**Comment by Sewer56** [comment]
This seems to be related to DirectInput ironically; and it's refusing to read from a device because it lost access.
I'll see what I can do later today :P; I'll probably just suppress the error for now.

I'll see to it in around an hour.

**Comment by Sewer56** [comment]
In the meantime, feel free to use the `XInput for Controller Hook` and disable `Custom Mapping for Controller Hook`.

**Comment by joaomiguel-sb** [comment]
Actually, when I use XInput for Controller Hook the Start button isn't mapped, so I can't start the game and when I use the keyboard to get In-Game, the Analog sticks don't work.
And less importantly the buttons are all mixed up, which can be fixed through the in-game button remapper.
I'm using DS4Windows which converts DirectInput to Xinput and Steam controller configuration thingy which also lets me use it as Xinput, in case you need that info.

![Zhr5bZaD9e](https://user-images.githubusercontent.com/80652132/111088842-e6e58980-8507-11eb-9399-4b86f717fcb5.jpg)
Also for some reason, I can't put Reloaded File Redirector according to this order:
TONNER
CRI FileSystem Hook
Reloaded File Redirector
SH Essentials: Graphics

Because whenever i change tabs, Reloaded File Redirector goes all the way down automatically, I know mod loading order is thing, I'm not sure if this is a problem or not, but I thought it was worth pointing out.
Hope this isn't too much of an issue, thanks for the help. :)

**Comment by joaomiguel-sb** [comment]
Kind of late, but i tested it and it's working perfectly!
Thank you so much for helping preserve this game!

**Comment by Sewer56** [comment]
Sorry for the delay; I'm job hunting and I've been depressed a bit lately.
Not much more I can say :/.

**Comment by joaomiguel-sb** [comment]
Don't worry about it, by late I meant that I took too long to check for updates and report back, I wasn't in a hurry to play Heroes, just setting it up, really.
I don't know what to say, but I hope things get better for you.
