### ISSUE TITLE
Vertical input is mapped incorrectly. 

### ISSUE THREAD

**Issue by pastelaura** [Sewer56/Heroes.Controller.Hook.ReloadedII#3]
Hello, I have an issue with vertical mapping. When I try mapping the left analog stick (Y) the controls get mapped inverted. For example in the game, moving up on the left analog stick goes downwards on the in-game menu and moving down on the left analog stick goes upwards on the in-game menu.

**Comment by Sewer56** [comment]
There's a mod called Post Processing for Controller Hook that lets you invert axis on your sticks, use that.

**Comment by pastelaura** [comment]
Where would I be able to download it?

**Comment by Sewer56** [comment]
Find it in 'Download Mods' menu
